FROM python:3.12-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

RUN apt-get update && apt-get install -y --no-install-recommends \
  libglib2.0-0 \
  libgl1 \
  && rm -rf /var/lib/apt/lists/*

RUN pip install \
  ultralytics \
  opencv-python-headless

RUN python -c "from ultralytics import YOLO; YOLO('yolov8n.pt')"

COPY detect-dog.py /app/detect-dog.py

CMD ["python", "-u", "/app/detect-dog.py"]
